### ISSUE TITLE
找不到 linux_text_input_gui.py 文件

### ISSUE THREAD

**Issue by picasso250** [xgenvn/InputHelper#11]
Ubuntu 14.04 Sublime 3 beta
通过 Package Control 安装，调用时报错（控制台）

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "inputhelper in /home/xiaochi/.config/sublime-text-3/Installed Packages/InputHelper.sublime-package", line 21, in run
  File "X/subprocess.py", line 818, in __init__
  File "X/subprocess.py", line 1416, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/home/xiaochi/.config/sublime-text-3/Packages/InputHelper/lib/linux_text_input_gui.py'
```

手动复制 InputHelper 文件夹至 /home/xiaochi/.config/sublime-text-3/Packages 下，可以解决此问题。

**Comment by xgenvn** [comment]
这个有关于 Sublime Text 3不自动解压插件包造成。之前有人修复过但是我已经删除掉，因为觉得大部分大家都使用git clone方法安装。加上过于复杂代码不是很需要。
