### ISSUE TITLE
Could not work on Ubuntu 12.04

### ISSUE THREAD

**Issue by JokerQyou** [xgenvn/InputHelper#12]
Hi I'm using Ubuntu 12.04 64bit, with Sublime Text 2 version 2.0.2 (build 2221) installed.
I installed InputHelper with Package Control. 
Each time I press `Ctrl + Shift + Z`, nothing happens, when I press <code>Ctrl + `</code> to view the console, the following error was printed:

``` python
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./inputhelper.py", line 21, in run
  File ".\subprocess.py", line 633, in __init__
  File ".\subprocess.py", line 1139, in _execute_child
OSError: [Errno 13] 权限不够
```

I've read all the issues under this repo, and found no solution so far. 

This information might also help: when I run `python linux_text_input_gui.py` in `lib` folder, the input box does appear, and after pressing `Enter`, the content is also printed in the terminal.

**Comment by JokerQyou** [comment]
Hi xgenvn!
I've found a way to solve this problem: change [line 19 of the file `inputhelper.py`](https://github.com/xgenvn/InputHelper/blob/master/inputhelper.py#L19). 

Before: 

``` python
args = [location]
```

After:

``` python
args = ['python2', location]
```

I'd like to open a pull request for this, but I can't do it now. If you see this, please fix this problem and close this issuse, thanks.

**Comment by xgenvn** [comment]
Please chmod the files under lib to 775 or 777.

**Comment by JokerQyou** [comment]
@xgenvn Yeah, that would work too. 
But why not use full arg list for subprocess? You could not expect every end-user to chmod that file after installing this package.

**Comment by xgenvn** [comment]
@JokerQyou I think we should not use the full arg list for subprocess, because it'll depend on python environment of end user. It would be python2, or python3, or anything else, it'll be complicated then. I supposed most of people using this plugin through typing **_git clone <this-repo>**_, so I have to cut off most of the important code (but also complex) to process the package uncompressing and chmod, the unicode print and grab the output, most of all is the compatibility between sublime 2 and 3.
I'll update and test all the cases when I have time. And thank you to your report. Hope this plugin help you out. And if you want something coming next, try out **_Atom Text Editor**_ by Github.

**Comment by JokerQyou** [comment]
@xgenvn Wow, I did not notice that. This plugin is very useful for those who don't want to change their input method. Thanks for your patience.

**Comment by geekwho-eth** [comment]
@xgenvn it works on ubuntu 14.04.
