### ISSUE TITLE
Ctrl + Shift +Z not work

### ISSUE THREAD

**Issue by cx-emerge** [xgenvn/InputHelper#17]
Ubuntu 16.04
Sublime Text 3 Build 3114

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "inputhelper in /home/gaoxiang/.config/sublime-text-3/Installed Packages/InputHelper.sublime-package", line 21, in run
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/home/gaoxiang/.config/sublime-text-3/Packages/InputHelper/lib/linux_text_input_gui.py'
```

**Comment by cntswj** [comment]
Cannot use shift-ctrl+z either, and with no error message...

**Comment by xgenvn** [comment]
Please check again the whether it exists under prompt location.
